lambdaclass/zksync-era

bin/zk
This PR changes the `bin/zk` script to unconditionally build the project. This improves the developer experience by not requiring to run first `zk` (to build the changes) and then `zk <cmd>` to do something.
Right now it is confusing what command to run. I thing this can be improved further by using a Makefile.
=> feat: Make zk script compile unconditionally

.gitignore, infrastructure/zk/src/run/run.ts
=> feat: Store native token in json

validium.md, validium_mode_example/src/main.rs
=> fix: update output readme

core/lib/web3_decl/src/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Adds a new RPC endpoint to get the Address of the native ERC20
it only adds a new method in the zks namespace.
This is needed by the explorer. More context here: https://github.com/lambdaclass/zksync-era/issues/31
You first need to run `zk init --native-erc20` to deploy the required contracts and generate the native_erc20.json file.
Then run the following command:
```bash
$ curl -X POST localhost:3050 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0", "method":"zks_getNativeTokenAddress", "params":[], "id":1}'
{"jsonrpc":"2.0","result":"0x2be576fb1996aeca500460c6691ce594a0aa98ae","id":1}
```
=> feat: Add native ERC20 token address endpoint

core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
Changes the native ERC20 address endpoint (get_native_token_address) to return a 0 if there is no native ERC20 deployed. This means that the native token in the network is ETH.
Since we are relying on the native_erc20.json file for now to detect a native ERC20 token, it just returns 0 if the files does not exist. In the future, If we move to config file we can check the existence/contents of the env var.
This is mostly added for compatibility purposes.
Just remove the `etc/tokens/native_erc20.json` file and query the endpoint:
```bash
❯ curl -X  POST http://localhost:3050 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"zks_getNativeTokenAddress","params":[""],"id":1}'
{"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000","id":1}
```
=> feat: handle eth case in native erc20 token address endpoint

core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/src/test-master.ts, core/tests/ts-integration/src/types.ts, infrastructure/zk/src/down.ts, yarn.lock
Closes #60 
Remove hardcoded variables to run native erc20 integration tests, set them only if `NATIVE_ERC20_ADDRESS` is set. As an extra, `zk down` has been updated to remove docker images/containers, useful for clean recompilations.
Have compatibility with `main`.
=> Fix: native erc20 fixes

core/tests/ts-integration/src/env.ts, infrastructure/zk/src/hyperchain_wizard.ts, infrastructure/zk/src/run/run.ts
Set a native token environment variable: `CONTRACTS_L1_NATIVE_ERC20_TOKEN_ADDR` on native token deployment.
**Note:** with the current implementation, if the previously mentioned env var is set, testing will be done with native token variables.
Prevent user from having to set token related environment variables manually, which is error prone.
=> feat: set native token env var

infrastructure/zk/src/init.ts
=> feat: fix zk init in rollup mode

core/tests/ts-integration/tests/system.test.ts
=> fix: system test for rollup

core/tests/ts-integration/src/helpers.ts, core/tests/ts-integration/tests/contracts.test.ts, core/tests/ts-integration/tests/system.test.ts
=> fix: tests using the new env var

core/tests/ts-integration/src/helpers.ts, core/tests/ts-integration/tests/contracts.test.ts, core/tests/ts-integration/tests/system.test.ts
=> Validium fix test new env value

core/lib/config/src/configs/chain.rs, core/lib/env_config/src/chain.rs, core/lib/zksync_core/src/lib.rs, etc/env/base/chain.toml
=> feat: Abstract commit data generator initialization

core/bin/external_node/src/main.rs, core/lib/config/src/configs/chain.rs, core/lib/env_config/src/chain.rs, core/lib/types/src/aggregated_operations.rs, core/lib/types/src/l1_batch_commit_data_generator.rs, core/lib/types/src/lib.rs, core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/lib/zksync_core/src/eth_sender/aggregator.rs, core/lib/zksync_core/src/eth_sender/publish_criterion.rs, core/lib/zksync_core/src/eth_sender/tests.rs, core/lib/zksync_core/src/lib.rs, etc/env/base/chain.toml
=> feat: Rename Validium abstraction and implementors

core/lib/config/src/configs/eth_sender.rs, core/lib/env_config/src/eth_sender.rs, core/lib/zksync_core/src/fee_model.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/mod.rs, core/lib/zksync_core/src/l1_gas_price/gas_adjuster/tests.rs, core/lib/zksync_core/src/state_keeper/io/tests/tester.rs, etc/env/base/eth_sender.toml
Closes[ Issue 70] (https://github.com/lambdaclass/zksync-era/issues/70)
=> feat: Not charging for pubdata

etc/env/base/chain.toml, etc/env/base/eth_sender.toml, infrastructure/zk/src/init.ts
=> Fix some comments

core/lib/config/src/testonly.rs
Fix:
```
Compiling zksync_config v0.1.0 (/zksync/zksync-era-lambda/core/lib/config)
error[E0063]: missing field `l1_gas_per_pubdata_byte` in initializer of `GasAdjusterConfig`
--> core/lib/config/src/testonly.rs:477:9
|
477 |         Self {
|         ^^^^ missing `l1_gas_per_pubdata_byte`
For more information about this error, try `rustc --explain E0063`.
error: could not compile `zksync_config` (lib) due to previous error
error: `cargo check` failed with status: exit status: 101
```
=> fix: missing structure fields in 'testonly.rs' 

Cargo.lock, core/lib/dal/sqlx-data.json, core/lib/l1_contract_interface/Cargo.toml, core/lib/types/src/l1_batch_commit_data_generator.rs
Merging this PR fixes: #111, #108, #109 and #110 
Removing `era-contracts-lambda` submodule as it is no longer necessary. Also removing `zksync-config` crate from `l1-contract-interface` as it is not used anymore. 
There is also a sql file created in the initialisation that should not be tracked. 
Finally there is a nit where empty structs don't need braces so it removes them. 
Removing unnecessary imports and repository files.
This pull request aims to streamline the repository by removing the now unnecessary `era-contracts-lambda` submodule and the `zksync-config` crate from `l1-contract-interface`. These changes have been made to clean up the codebase, removing unused dependencies and files.
After applying these changes, running the following commands should complete successfully …
=> fix: Delete unused config files in validium pubdata abstraction 

core/bin/external_node/src/main.rs, core/lib/l1_contract_interface/src/i_executor/structures/commit_batch_info.rs, core/lib/protobuf_config/src/proto/chain.proto, core/lib/protobuf_config/src/proto/eth_sender.proto, validium_mode_example/src/main.rs
=> fix: protobuf and lint fixes

core/tests/ts-integration/src/context-owner.ts, core/tests/ts-integration/src/env.ts, core/tests/ts-integration/src/types.ts, core/tests/ts-integration/tests/non-native-erc20-deposit.test.ts, infrastructure/local-setup-preparation/src/index.ts, infrastructure/zk/src/contract.ts, infrastructure/zk/src/init.ts, sdk/zksync-rs/src/ethereum/mod.rs, yarn.lock
Change contracts submodule to work with native token implementation alongside ETH
```bash
npm run dev -- wallet balance --chain=local-geth --address=0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE --erc20-address=0xD47a77a7A93c099a451a2c269ea5fB35238dC52c && npm run dev -- wallet balance --chain=local-geth --address=0x52312AD6f01657413b2eaE9287f6B9ADaD93D5FE
```
**Expected output:**
```bash
...
Local GETH Node Balance: 300000000030000000000039999911200551425000003 lambdacoin
...
Local GETH Node Balance: 3125000000000000005.235779057152336709 ETH
```
```bash
npm run dev -- bridge deposit --chain=dockerized-node --token=0xD47a77a7A93c099a451a2c269ea5fB35238dC52c --pk=0xe131bc3f481277a8f73d680d9ba404cc6f959e64296e0914dded403030d4f705 --to=0x25E62AdC9d1BA5541A30814fbd6cf5efd14C129e …
```
=> feat: Native erc20 contract fixes

core/lib/types/src/l1_batch_commit_data_generator.rs
As it says in the issue, we need to add this `Bytes([0])` as `pubdata` in the **Validium commit data** to match the ABI encoding.
This is checked in `consistency_checker` tests: this change is required to pass tests in validium mode. You can see more details in [this PR](https://github.com/lambdaclass/zksync-era/pull/121) description.
=> feat:  Match ABI encoding adding `bytes pubdata` at the end of the encoding in Validium's commit data

core/lib/types/src/l1_batch_commit_data_generator.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
```
assertion `left == right` failed
left: Tuple([Uint(1), Uint(1), Uint(21), FixedBytes([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), Uint(0), FixedBytes([197, 210, 70, 1, 134, 247, 35, 60, 146, 126, 125, 178, 220, 199, 3, 192, 229, 0, 182, 83, 202, 130, 39, 59, 123, 250, 216, 4, 93, 133, 164, 112]), FixedBytes([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), FixedBytes([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), Bytes([]), Bytes([0])])
right: Tuple([Uint(1), Uint(1), Uint(21), FixedBytes([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]), Uint(0), FixedBytes([197, 210, 70, 1, 134, 247, …
```
=> feat: adapt `consistency_checker` tests for running both in Validium mode and Rollup mode

core/lib/env_config/src/eth_sender.rs
Closes #134 
This pull request introduces enhancements to the existing test suite for the ETHSenderConfig in the env_config crate. The primary goal is to create dedicated configurations for Rollup and Validium scenarios and provide specific tests for each.
New Test Configurations:
- Two new functions, rollup_expected_config and validium_expected_config, have been added to generate configurations tailored for Rollup and Validium use cases.
- Additional Test Methods: Two new test methods, rollup_from_env and validium_from_env, have been implemented to specifically test Rollup and Validium configurations, respectively.
- Validium Configuration Adjustment: The validium_expected_config function now sets the l1_gas_per_pubdata_byte field to 0 for Validium, reflecting the required Validium …
=> feat: adapt `zksync_env_config::eth_sender` tests for running both in Validium mode and Rollup mode

core/lib/env_config/src/chain.rs
Update the `zksync_env_config::chain` test of `state_keeper_from_env` to take into account the Rollup and Validium mode settings and check that both settings are modified correctly.
I have separated the `expected_state_keeper_config()` into two functions to manage the `StateKeeperConfig` for both modes and updated `state_keeper_from_env()` test to compare the new mockup configuration and the `StateKeeperConfig` of the Validium mode.
```
zk test rust --package zksync_env_config --lib -j 1 -- chain::tests
```
=> feat: adapt `zksync_env_config::chain` tests for running both in Validium mode and Rollup mode

core/bin/external_node/src/main.rs, core/lib/zksync_core/src/consistency_checker/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
=> Add `l1_batch_commit_data_generator` as parameter to the `ConsistencyChecker` structure

core/lib/web3_decl/src/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
=> fix: Use `zksync_types::Bytes` instead of `Vec<u8>`

.gitignore, Makefile, etc/env/main_demo_rollup_blobs.toml, etc/env/main_demo_validium_blobs.toml, validium_mode_example/README.md, validium_mode_example/src/constants.rs, validium_mode_example/src/helpers/mod.rs, validium_mode_example/src/helpers/tx_kind.rs, validium_mode_example/src/main.rs, validium_mode_example/src/scenario.rs
=> feat: Add blobs execution to example

core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
=> Test CALL opcode

core/lib/dal/src/models/storage_transaction.rs, core/lib/multivm/src/versions/vm_latest/tests/evm_simulator.rs
Add handling for eth native transactions, where the "to" field is set to 0, null or 0x.
=> Handle eth tx with 0x

core/lib/multivm/src/lib.rs, core/lib/multivm/src/versions/era_vm/event.rs, core/lib/multivm/src/versions/era_vm/snapshot.rs, core/lib/multivm/src/versions/era_vm/vm.rs, core/lib/multivm/src/versions/mod.rs
Adapts the `era_vm` to the new world struct. Merge once [this pr](https://github.com/lambdaclass/era_vm/pull/197) gets merged.
=> Adapt era_vm to new world struct

core/lib/multivm/src/versions/era_vm/bytecode.rs, core/lib/multivm/src/versions/era_vm/vm.rs
Adapts vm to new Storage changes necessary for pubdata and refunds implementation. See [here](https://github.com/lambdaclass/era_vm/pull/200/files).
=> Adapt era_vm to new Storage

core/lib/prover_interface/src/inputs.rs, core/node/vm_runner/src/impls/bwip.rs, prover/crates/bin/witness_generator/src/basic_circuits.rs
=> EVM Simulator code hash in witness data

core/lib/multivm/src/versions/era_vm/vm.rs
Fixes the return value when running opcodes. The `blob_tracer` isn't part part of the result anymore.
=> Fix blob_tracer return when running program

core/lib/config/src/configs/mod.rs, core/lib/config/src/configs/use_evm_simulator.rs, core/lib/contracts/src/lib.rs, core/lib/env_config/src/lib.rs, core/lib/env_config/src/use_evm_simulator.rs, etc/env/base/use_evm_simulator.toml
=> feat: make evm simulator optional for the server

core/lib/config/src/configs/da_dispatcher.rs, core/lib/config/src/testonly.rs, core/lib/env_config/src/da_dispatcher.rs, core/lib/protobuf_config/src/da_dispatcher.rs, core/lib/protobuf_config/src/proto/config/da_dispatcher.proto, core/node/da_dispatcher/src/da_dispatcher.rs
=> feat: concurrent da_dispatcher

.gitignore, backup-ecosystem.sh, eigenda-integration.md, restore-ecosystem.sh
Docs on EigenDA integration, and scripts to bakcup and restore an ecosystem.
=> feat: Da eigen implementation docs & backup scripts

core/bin/zksync_server/src/node_builder.rs, core/lib/config/src/configs/da_client/eigen_da.rs, core/lib/protobuf_config/src/da_client.rs, core/lib/protobuf_config/src/proto/config/da_client.proto, core/node/da_clients/src/eigen_da.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen_da.rs, core/node/node_framework/src/implementations/layers/eigenda_proxy.rs, eigenda-integration.md
This PR adds some new configs necessary now that the proxy is not going to be used anymore.
We may need more or less fields in the future, this is just to get ahead.
Some configs like `api_node_url` will need to be removed once we remove the eigenda proxy, but for now to preserve functionality until rust proxy is finished I just left comments were removal would be necessary.
There are two variants:
```yaml
da_client:
eigen_da:
memstore:
api_node_url: http://127.0.0.1:4242 # TODO: This should be removed
max_blob_size_bytes: 2097152
blob_expiration: 100000
get_latency: 100
put_latency: 100
```
```yaml
da_client:
eigen_da:
disperser:
api_node_url: http://127.0.0.1:4242 # TODO: This should be removed
disperser_rpc: <your_desired_disperser>
eth_confirmation_depth: -1
eigenda_eth_rpc: …
```
=> feat: Eigenda Config

core/lib/config/src/configs/da_client/eigen.rs, core/lib/protobuf_config/src/da_client.rs, core/lib/protobuf_config/src/proto/config/da_client.proto, core/node/da_clients/src/eigen/client.rs, eigenda-integration.md, yarn.lock
This PR re implements the config for eigen. With memstore and disperser options
Recompile `zkstack`:
`cargo install --path zkstack_cli/crates/zkstack --force --locked
`
If you want to use memstore:
```yaml
da_client:
eigen:
mem_store:
max_blob_size_bytes: 2097152
blob_expiration: 100000
get_latency: 100
put_latency: 100
```
If you want to use disperser:
```yaml
da_client:
eigen:
disperser:
disperser_rpc: <your_desired_disperser>
eth_confirmation_depth: -1
eigenda_eth_rpc: <your_desired_rpc>
eigenda_svc_manager_address: '0xD4A7E1Bd8015057293f0D0A557088c286942e84b'
blob_size_limit: 2097152
status_query_timeout: 1800
status_query_interval: 5
wait_for_finalization: false
authenticated: false
```
=> feat(eigen-client-extra-features): Reimplement eigen config

Cargo.lock, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/blob_info.rs, core/node/da_clients/src/eigen/mod.rs, core/node/da_clients/src/eigen/sdk.rs
Implement rlp encoding for the dispersed blob.
=> feat(eigen-client-extra-feature): rlp encoding

core/node/da_clients/src/eigen/client.rs
Implement inclusion data retrieval for the Eigen DA client.
=> feat(eigen-client-extra-features): get inclusion data

Cargo.lock, core/lib/config/src/configs/da_client/eigen.rs, core/lib/env_config/src/da_client.rs, core/lib/protobuf_config/src/da_client.rs, core/lib/protobuf_config/src/proto/config/da_client.proto, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/client.rs
This PR removes the config parameter custom quorum numbers for the disperser, which is not used anywhere
=> feat(eigen-client-extra-features): Remove unused custom quorum numbers

core/lib/config/src/configs/da_dispatcher.rs, core/lib/config/src/testonly.rs, core/lib/dal/.sqlx/query-0fdfa0f31142899f3d5f808688d76ec553688e69dfd330ca408505b8b2cdee5e.json, core/lib/dal/src/data_availability_dal.rs, core/lib/env_config/src/da_dispatcher.rs, core/lib/protobuf_config/src/da_dispatcher.rs, core/lib/protobuf_config/src/proto/config/da_dispatcher.proto, core/node/da_dispatcher/src/da_dispatcher.rs, core/node/da_dispatcher/src/metrics.rs
Implement concurrent data availability dispatcher, to greatly reduce dispersing time when there are many blobs due dispersing.
=> feat(eigen-client-m0-implementation): concurrent da dispatcher

core/node/da_clients/src/eigen/sdk.rs, core/node/da_dispatcher/src/da_dispatcher.rs
This PR fixes a bug with concurrent dispatcher, where the loop was never stopped so the pending blobs sender thread never stopped, so no error was shown when a dispatched failed.
=> Fix concurrent dispatcher

core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/sdk.rs
This PR moves inclusion and verify logic from disperse blob to get inclusion data
=> feat(eigen-client-extra-features): Move inclusion logic

core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs
This PR removes verify cert variable
=> feat(eigen-client-extra-features): Remove verify cert

core/bin/zksync_server/src/node_builder.rs, core/lib/config/src/configs/da_client/eigen.rs, core/lib/env_config/src/da_client.rs, core/lib/protobuf_config/src/da_client.rs, core/node/da_clients/src/eigen/README.md, core/node/da_clients/src/eigen/client_tests.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs
This PR fixes the last comments from client PR
=> feat(eigen-client-extra-features): Fix PR comments

get_all_blobs/src/client.rs, get_all_blobs/src/main.rs
Minimal changes to `get_all_blobs` in order to accomodate to latest changes in codebase.
=> fix(eigen-client-m0-implementation): fix get all blobs program

core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/client_tests.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs
- [use trait object to avoid parametrization](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888711967)
- [use `spawn_blocking`](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888737510)
=> feat(eigen-client-extra-features): address PR comments (part 5)

core/lib/config/src/configs/da_client/eigen.rs, core/lib/dal/migrations/20241812144402_create_index_data_availability.sql, core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/client_tests.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs, core/node/da_clients/src/eigen/verifier_tests.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs
[`data_availability` full scan](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888687629)
[simpler ABI decoding](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888803680)
[infalible cast](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888781030)
[default disperser_rpc](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888672059)
[replace `String` with `Url`](https://github.com/matter-labs/zksync-era/pull/3243#discussion_r1888718196)
=> feat(eigen-client-extra-features): address PR comments (part 4)

core/lib/config/src/configs/da_client/eigen.rs, core/lib/dal/migrations/20241812144402_create_index_data_availability.sql, core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/client_tests.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs, core/node/da_clients/src/eigen/verifier_tests.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs
=> feat(eigen-client-extra-features): address PR comments (part 3)

core/lib/config/src/configs/da_client/eigen.rs, core/lib/dal/migrations/20241812144402_create_index_data_availability.sql, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/client_tests.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs, core/node/da_clients/src/eigen/verifier_tests.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs
=> feat(eigen-client-extra-features): address PR comments (part 2)

zkstack_cli/crates/config/src/chain.rs, zkstack_cli/crates/zkstack/src/commands/chain/args/init/da_configs.rs, zkstack_cli/crates/zkstack/src/commands/chain/args/init/mod.rs, zkstack_cli/crates/zkstack/src/commands/chain/init/configs.rs, zkstack_cli/crates/zkstack/src/commands/chain/init/mod.rs
This PR adds the eigenda option to zkstack
It also updates the contracts submodule to `eigen-client-m1` branch
=> feat(eigen-client-m1): Add eigenda to zkstack
