infrastructure/zk/src/init.ts
Re adds the step where the WETH token was deployed.
=> feat: Re-add WETH deploy

infrastructure/zk/src/contract.ts, infrastructure/zk/src/init.ts
=> feat: Uncomment steps

hardhat.config.ts
=> fix: hardhat error

.dockerignore
=> fix: exclude validium_mode_example from .dockerignore

core/lib/types/src/l1_batch_commit_data_generator.rs, core/lib/zksync_core/src/consistency_checker/tests/mod.rs, core/lib/zksync_core/src/consistency_checker/tests/test_helpers.rs
=> fix: update function visibility in `consistency_checker` tests

core/tests/ts-integration/tests/withdraw.test.ts
=> Fix withdraw tests

core/lib/web3_decl/src/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs
=> feat: rename native (base) token address endpoint and return 0x0..01 with eth base token

core/lib/web3_decl/src/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/namespaces/zks.rs, core/lib/zksync_core/src/api_server/web3/namespaces/zks.rs, core/tests/ts-integration/src/env.ts
Closes #149, _**be sure to merge this one after #148.**_
=> feat: avoid using env var for testing native erc20

core/lib/types/src/commitment.rs, core/lib/types/src/l1_batch_commit_data_generator.rs, core/lib/types/src/utils.rs
Pull Request Description:
Closes #141 
Changes Made:
Rollbacks construct_pubdata method from `core/lib/types/src/utils.rs` to `core/lib/types/src/commitment.rs`.
=> feat: Rollback `construct_pubdata` method. 

core/lib/web3_decl/src/error.rs, core/lib/zksync_core/src/api_server/web3/backend_jsonrpsee/mod.rs
=> fix: Remove unused error

core/lib/multivm/src/versions/era_vm/hook.rs, core/lib/multivm/src/versions/era_vm/vm.rs
This PR fixes missing hooks, in order to be able to run benchmarks.
=> Fix hook 7 for benchmarks

core/lib/multivm/src/versions/era_vm/vm.rs
The last commit broke the hooks implementation, this pr reverts the commit.
=> Revert last commit that was breaking era_vm

core/tests/vm-benchmark/benches/criterion.rs
=> Fix: Leverage zksync home to fetch benchmark paths

core/lib/multivm/src/versions/era_vm/tests/tester/transaction_test_info.rs, core/lib/multivm/src/versions/era_vm/vm.rs
Adapt to [this PR](https://github.com/lambdaclass/era_vm/pull/209)
=> Adapt zksync era to private fields on Rollbackable structs

core/node/da_clients/src/eigen_da.rs
Implement `get_inclusion_data` for `EigenDAClient`.
=> fix: EigenDA retrieve blob logic

.github/workflows/ci-core-reusable.yml, core/lib/config/src/configs/da_client/mod.rs, core/lib/protobuf_config/src/da_client.rs, core/node/da_clients/Cargo.toml
=> eigenda-implementation merge main

.github/workflows/ci-common-reusable.yml, .github/workflows/ci-core-lint-reusable.yml, .github/workflows/ci-core-reusable.yml, .github/workflows/ci-docs-reusable.yml, .github/workflows/ci-prover-reusable.yml, .github/workflows/vm-perf-comparison.yml, .github/workflows/vm-perf-to-prometheus.yml, core/lib/protobuf_config/src/da_client.rs, core/tests/ts-integration/hardhat.config.ts, core/tests/ts-integration/tests/api/contract-verification.test.ts, zk_toolbox/crates/zk_supervisor/src/commands/test/integration.rs
=> eigenda implementation merge main

etc/env/file_based/general.yaml, retrieve-blobs/src/main.rs, zk_toolbox/crates/common/src/git.rs, zk_toolbox/crates/config/src/consts.rs, zk_toolbox/crates/zk_inception/src/commands/ecosystem/setup_observability.rs
This PR adds necessary changes in order to deploy locally using the zk toolbox and eigenda
=> feat: EigenDA Toolbox

get_all_blobs/getallblobs.js
This PR fixes a bug were the get all blobs script did not retrieve all blobs due to concurrency problems
=> fix: Get blob from L1

core/lib/config/src/configs/da_client/eigen.rs, core/lib/env_config/src/da_client.rs, core/lib/env_config/src/lib.rs, core/lib/protobuf_config/src/da_client.rs
Fix test related to `EigenConfig`, broken after #320 
Make all tests pass
=> fix(eigen-client-extra-features): fix eigen config test

core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/sdk.rs, core/node/da_clients/src/eigen/verifier.rs
This PR adds use of eth confirmation depth parameter, now verification is done in a loop until it is verified or time is expired.
=> feat(eigen-client-extra-features): Eth confirmation depth

Cargo.lock, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/sdk.rs
This PR removes kzgpad dependency.
=> feat(eigen-client-extra-features): Remove kzgpad

core/node/da_clients/src/eigen/verifier.rs
This PR beautifies the import of eigenDAServiceManager
=> feat(eigen-client-extra-features): Import eigenDAServiceManager

core/node/da_clients/src/eigen/sdk.rs
This PR changes authenticated match to an if
=> feat(eigen-client-extra-features): Change authenticated match to if

Cargo.lock, Cargo.toml, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/sdk.rs
This PR moves dependencies to workspace
=> feat(eigen-client-eigen-features): Move dependencies

core/lib/protobuf_config/src/proto/config/da_client.proto
=> Remove extra config

Cargo.lock, Cargo.toml, core/lib/protobuf_config/src/proto/config/da_client.proto
This PR uses rust-kzg-bn254 crate instead of using its github page
=> feat(eigen-client-extra-features): Kzg bn254 crate

core/lib/protobuf_config/src/da_client.rs, core/node/da_clients/src/eigen/sdk.rs
=> Eigen client solve comments

core/Cargo.lock
This PR fixes cargo deny step in CI
To reproduce run:
`cargo install --locked cargo-deny`
`cargo deny check`
=> feat(extra-features): Fix cargo deny

zkstack_cli/crates/config/src/chain.rs, zkstack_cli/crates/config/src/contracts.rs, zkstack_cli/crates/config/src/forge_interface/deploy_ecosystem/input.rs, zkstack_cli/crates/config/src/forge_interface/deploy_ecosystem/output.rs, zkstack_cli/crates/config/src/forge_interface/deploy_l2_contracts/input.rs, zkstack_cli/crates/types/src/l1_network.rs, zkstack_cli/crates/zkstack/src/commands/chain/init/mod.rs
=> feat(extra-features): Remove validators

core/Cargo.lock, core/Cargo.toml, core/node/da_clients/Cargo.toml, core/node/da_clients/src/eigen/client.rs, core/node/da_clients/src/eigen/mod.rs, core/node/node_framework/src/implementations/layers/da_clients/eigen.rs, etc/env/file_based/general.yaml
=> chore: Update client crate
